#
# Chef Server Config File
#
# Dynamically generated by Chef - local modifications will be replaced

log_level          :info
log_location       STDOUT
ssl_verify_mode    :verify_none
chef_server_url    "http://chef.private.org:4000"

couchdb_database   'chef'

cookbook_path      [ "/srv/chef/cookbooks", "/srv/chef/site-cookbooks" ]
cookbook_tarball_path "/srv/chef/cache/cookbook-tarballs"

file_cache_path    "/srv/chef/cache"
node_path          "/srv/chef/nodes"
openid_store_path  "/srv/chef/openid/store"
openid_cstore_path "/srv/chef/openid/cstore"
search_index_path  "/srv/chef/search_index"
role_path          "/srv/chef/roles"

validation_client_name "chef-validator"
validation_key         "/etc/chef/validation.pem"
client_key             "/etc/chef/client.pem"
web_ui_client_name     "chef-webui"
web_ui_key             "/etc/chef/webui.pem"

web_ui_admin_user_name "admin"

supportdir = "/srv/chef/support"
solr_jetty_path File.join(supportdir, "solr", "jetty")
solr_data_path  File.join(supportdir, "solr", "data")
solr_home_path  File.join(supportdir, "solr", "home")
solr_heap_size  "256M"

umask 0022

signing_ca_cert    "/etc/chef/certificates/cert.pem"
signing_ca_key     "/etc/chef/certificates/key.pem"
signing_ca_user    "root"
signing_ca_group   "root"
