#
# Chef SOLR Config File
#
# Dynamically generated by Chef - local modifications will be replaced

log_location       STDOUT

search_index_path    "/srv/chef/search_index"

supportdir = "/srv/chef/support"
solr_jetty_path File.join(supportdir, "solr", "jetty")
solr_data_path  File.join(supportdir, "solr", "data")
solr_home_path  File.join(supportdir, "solr", "home")
solr_heap_size  "256M"

solr_url        "http://localhost:8983"

amqp_pass "testing"
