Vagrant::Config.run do |config|

  @cc_box_name  = "bbb"
  @cc_node_name = "bbb"
  @cc_ip        = "33.33.33.3"                          # Change if already in use
  @cc_http_port = 48623                                 # ditto
  @cc_ssh_port  = 48622                                 # ditto
  @cc_chef_server_url     = "http://33.33.33.10:4000"   # ditto
  @cc_root_path           = File.dirname(File.absolute_path(__FILE__))
  @cc_box_url             = "#{File.dirname(File.dirname(File.dirname(@cc_root_path)))}/lucid64_4.0.4.box"
  @cc_host_mount          = "#{@cc_root_path}/etc"
  @cc_chefserver_path     = File.dirname(File.dirname(File.dirname(@cc_root_path)))
  @cc_validation_key_path = "#{@cc_chefserver_path}/chefserver/etc/validation.pem"

  config.vm.customize do |vm|

    vm.memory_size = 1024
    vm.vram_size = 12
    vm.cpu_count = 2
    vm.accelerate_3d_enabled = false
    vm.accelerate_2d_video_enabled = false
    vm.monitor_count = 1

    vm.bios.acpi_enabled = true
    vm.bios.io_apic_enabled = false

    vm.cpu.pae = true

    vm.hw_virt.enabled = false
    vm.hw_virt.nested_paging = false
    # STORAGE
  end

  config.vm.box = @cc_box_name
  config.vm.box_url = @cc_box_url
  config.vm.boot_mode = :vrdp # :vrdp (headless) or :gui (window system)

  config.vm.network @cc_ip
  config.vm.forward_port "http", 80, @cc_http_port
  config.vm.forward_port "ssh", 22, @cc_ssh_port, :auto => true  

  config.vm.share_folder "chef", "~/chef", "~/chef"
  config.vm.share_folder( "chef-client-etc", "/etc/chef", @cc_host_mount ) # name, /vm/path, /host/path

  config.vm.provision :chef_server do |chef|  
     chef.log_level = :debug
     chef.node_name = @cc_node_name     
     chef.chef_server_url = @cc_chef_server_url
     chef.validation_key_path = @cc_validation_key_path
     chef.validation_client_name = "chef-validator"
     chef.add_role("bbb")
   end
end
